[package]
name = "triggers"
version = "0.1.0"
edition.workspace = true

[dependencies]
dag = { path = "../dag" }
fnmatch = { path = "../fnmatch" }

serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_yaml.workspace = true
